from turtle import screensize
import pygame,os

TITLE='Puzzle Bobble'
SCALE=3
SCREEN_SIZE=SCREEN_WIDTH,SCREEN_HEIGHT=320*SCALE,224*SCALE # 1280,896
STAGE_SIZE=STAGE_WIDTH,STAGE_HEIGHT=130*SCALE,200*SCALE # 520,800
GRID_CELL_SIZE=8*SCALE
FPS=60

CURRENT_PATH=os.path.dirname(os.path.abspath(__file__))
IMAGE_PATH=os.path.join(CURRENT_PATH,'image')