from turtle import screensize
import pygame,os

SCALE=4
GRID_CELL_SIZE=8*SCALE
STAGE_CELL_SIZE=14*SCALE
STAGE_ROW,STAGE_COLUMN=11,8
BUBBLE_SIZE=BUBBLE_WIDTH,BUBBLE_HEIGHT=16*SCALE,16*SCALE
BUBBLE_LOAD_POS=640,768

TITLE='Puzzle Bobble'
SCREEN_SIZE=SCREEN_WIDTH,SCREEN_HEIGHT=320*SCALE,224*SCALE # 1280,896
STAGE_SIZE=STAGE_WIDTH,STAGE_HEIGHT=128*SCALE,160*SCALE
STAGE_LEFT,STAGE_RIGHT,STAGE_TOP,STAGE_BOTTOM=GRID_CELL_SIZE*12,GRID_CELL_SIZE*28,GRID_CELL_SIZE*3,STAGE_HEIGHT
FPS=60

CURRENT_PATH=os.path.dirname(os.path.abspath(__file__))
IMAGE_PATH=os.path.join(CURRENT_PATH,'image')